<?php
include 'ArrayValidate.class.php';
if (!empty($_POST)) {

    $ArrayValidate = new ArrayValidate();

    /**
     * Add new label, validation or format.
     * $ArrayValidate->setConfig(
     *      array(
     *          ****
     *      )
     * );
     *
     *
     * === Index ===
     *
     * "lb_erro" => Labels Erro, change the "?" the desired value.
     * Example:
     * "lb_erro" => array(
     *      "maxlength" => "Field ?, can not be greater than ? characters."
     * )
     *
     * "validates" => Validations, Create your own validation.
     * $valid => value method. eg "notnull" => true, $valid => true;
     * $valObj => field value;
     * $key => field index;
     * $label => field label;
     * Example:
     * "validates" => array(
     *     "maxlength" =>
     *          'if (strlen($valObj) > intval($valid)) {
     *          $this->construct_erro("maxlength", array($label,$valid));
     *      }'
     * )
     * $this->construct_erro => call label error "maxlength", send parameters array($label,$valid) to change "?"
     *
     *
     * "format" => Format, format the return value.
     * $valObj => field value;
     * $key => field index;
     * $label => field label;
     * Example:
     *
     * "format" => array(
     *      "convertNumber" => '$this->construct_rs($key, preg_replace("/\D/", "", $valObj));'
     * )
     * $this->construct_rs => construct return result, send parameters key more value.
     */

    //Example setConfig.
    $ArrayValidate->setConfig(
        array(
            "lb_erro" => array(
                "type_integer" => "Field ?, invalid number."
            ),
            "validates" => array(
                "numeric" =>
                    'if($valid === true && !is_numeric($valObj)){
                    $this->construct_erro("type_integer", array($label));
                }'
            )
        )
    );

    /**
     * Rules
     */
    $valid = array(
        "name" => array(
            "label" => "Name",
            "validates" => array(
                "notnull" => true,
                "maxlength" => 10,
                "minlength" => 4
            )
        ),
        "lastname" => array(
            "label" => "Last Name",
            "validates" => array(
                "notnull" => true,
                "maxlength" => 10,
                "minlength" => 4,
            )
        ),
        "age" => array(
            "label" => "Age",
            "validates" => array(
                "notnull" => true,
                "maxlength" => 3,
                "minlength" => 2,
                "numeric" => true
            )
        ),
        "convertNumber" => array(
            "label" => "Convert Number",
            "validates" => array(
                "maxlength" => 10
            ),
            "format" => "convertNumber"
        ),
        "convertDate" => array(
            "label" => "Convert Date",
            "validates" => array(
                "notnull" => true,
                "dateValid" => true
            ),
            "format" => "date"
        )
    );

    $rs = $ArrayValidate->margeValidate($valid, $_POST);

}
?>

<html>
<head>
    <title>PHP-Array-Validate</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <form method="post" action="" style="margin-top:30px;margin-bottom:30px;">
        <fieldset>
            <legend>Validate Form</legend>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Name</label>
                        <input class="form-control" name="name" placeholder="Name" type="text"
                               value="<?php echo (isset($_POST['name'])) ? $_POST['name'] : ''; ?>">

                        <p class="help-block">Not null, maxlength 10, minlength 4.</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Last Name</label>
                        <input class="form-control" name="lastname" placeholder="Last Name" type="text"
                               value="<?php echo (isset($_POST['lastname'])) ? $_POST['lastname'] : ''; ?>">

                        <p class="help-block">Not null, maxlength 10, minlength 4.</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Age</label>
                        <input class="form-control" name="age" placeholder="Age" type="text"
                               value="<?php echo (isset($_POST['age'])) ? $_POST['age'] : ''; ?>">

                        <p class="help-block">Not null, maxlength 3, minlength 2, type numeric.</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Convert Number</label>
                        <input class="form-control" name="convertNumber" placeholder="Convert Number" type="text"
                               value="<?php echo (isset($_POST['convertNumber'])) ? $_POST['convertNumber'] : ''; ?>">

                        <p class="help-block">Maxlength 10, format convert number.</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label">Convert Date</label>
                        <input class="form-control" name="convertDate" placeholder="MM/DD/YYYY" type="text"
                               value="<?php echo (isset($_POST['convertDate'])) ? $_POST['convertDate'] : ''; ?>">

                        <p class="help-block">Not null, format date.</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-primary btn-block" type="submit">Validate</button>
                </div>
            </div>
        </fieldset>
    </form>

    <?php if (isset($rs)): ?>
        <h3>Result</h3>
        <pre><?php var_dump($rs) ?></pre>
    <?php endif ?>
</div>
</body>
</html>
